# Generated by Django 5.2.1 on 2025-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
