# Generated by Django 5.2.1 on 2025-06-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_savedarticle_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='title',
        ),
    ]
