# Generated by Django 5.2.1 on 2025-06-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_title_remove_repo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Untitled', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='title',
            field=models.CharField(default='Untitled', max_length=500),
            preserve_default=False,
        ),
    ]
