# Generated by Django 5.2.1 on 2025-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_title_repo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
