version: '3.8'

services:
  frontend:
    build:
      context: ./devpulse_frontend    # chemin vers le Dockerfile frontend
    ports:
      - "3000:3000"         # expose frontend sur localhost:3000
    restart: unless-stopped

  web:
    build:
      context: ./devpulse_backend     # chemin vers le Dockerfile backend
    command: gunicorn devpulse_backend.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120 --log-level debug
    volumes:
      - ./devpulse_backend:/app       # monte le code backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine

  celery:
    build:
      context: ./devpulse_backend
    command: celery -A devpulse_backend worker --loglevel=info
    volumes:
      - ./devpulse_backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
