name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy deploy script to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "deploy.sh"
        target: ${{ secrets.DEPLOY_DIR }}

    - name: Run deploy script on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          chmod +x ${{ secrets.DEPLOY_DIR }}/deploy.sh
          cd ${{ secrets.DEPLOY_DIR }}
          ./deploy.sh
          docker compose pull
          docker compose up -d --build
